server:
  port: 9003

spring:

  mvc:
    view:
      pathmatch:
        use-suffix-pattern: false
        use-registered-suffix-pattern: true
      contentnegotiation:
        favor-path-extension: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl

    content-type: text/html
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: '0.##'
      classic_compatible: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.138.204.175:3306/video?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapUnderscoreToCamelCase: true
  mapperLocations: classpath:mapper/*.xml


logging:
  level:
    root: INFO





    
